### ISSUE TITLE
Failed Save - partially completed

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3582]
This is probably a matter of taste, but current behaviour is unpalatable to me.

With a new file, File/Save to a location you do not have write permission, give it a proper filename in the save dialogue.
Gets a dialogue box with the following (and in console)
```
Failed to open file for writing /usr/share/openscad-nightly/examples/Basics/sphere-chopped.scad (Permission denied)
```
OK so far.

But it then progresses to give the Tab/Title the new filename.
I would expect it to be an atomic operation, if the save fails, the 'untitled.scad' instance stays as it was.

This also happens with Save-As, the editor takes on the new filename, even though it does not exist.
Also the `*` in the Tab/Title, signifying editor has changes, is no longer shown,
although if you close it, you do get the 'file changed' prompt.

This was on Debian w 2020.12.15.

**Comment by t-paul** [comment]
Can you verify with the latest snapshot? I believe that is fixed via #3576.

**Comment by MichaelAtOz** [comment]
![Screenshot from 2021-01-05 10-35-21](https://user-images.githubusercontent.com/1972961/103590437-f95ca900-4f41-11eb-92bd-7942f0cb01eb.png)
Nope, not fixed, 2020.01.03-nightly, File/New, File/Save, select un-writable directory, give it a name 'save-bug.scad', write error, but editor takes on new name. And same with Save-as, including loss of `*`.

I'll give it a go on Windows.

**Comment by MichaelAtOz** [comment]
I'm not a Windows security permissions specialist, I just setup a directory and selected Deny-write.

On Windows, something checks whether it can be written at the Save dialogue box level.

![Capture-save-as-bug](https://user-images.githubusercontent.com/1972961/103591565-a2a49e80-4f44-11eb-9f36-3da70765bbd2.JPG)

Given the dialogue is still open, I assume that something is Windows not OpenSCAD??

**Comment by t-paul** [comment]
Aha, the change I had in mind did cover the recent list, not the editor path update.
