### ISSUE TITLE
Windows cmake error: `missing: HARFBUZZ_INCLUDE_DIRS`

### ISSUE THREAD

**Issue by Paulwhy2** [openscad/openscad#4328]
Hi, I am trying to compile openscad to contribute in Windows. I'm following these instructions: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Microsoft_Windows

When running CMAKE:
```
cmake .. -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON
```

I get the error:
```
-- Boost: 1.79.0
CMake Error at C:/msys64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find HarfBuzz (missing: HARFBUZZ_INCLUDE_DIRS) (Required is at
  least version "0.9.19")
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindHarfBuzz.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:278 (find_package)
```

However, I do have Harfbuzz installed with pacman and I verified that I have the file `hb.h`. I think that something is wrong with the cmake file [FindHarfBuzz.cmake](https://github.com/openscad/openscad/blob/ea8950bd3cd7f06da333c15463492e484098e591/cmake/Modules/FindHarfBuzz.cmake) but I'm not familiar with cmake and I wonder if anyone who compiles on windows would be able to more easily debug this.

Thanks!

**Comment by Paulwhy2** [comment]
I fixed it. I added the path to the hb.h file to the CMakeOutput.log file, and saved saved it:

//Path to a file.
HARFBUZZ_INCLUDE_DIRS:PATH=C:\msys64\mingw64\include\harfbuzz

**Comment by jordanbrown0** [comment]
Unfortunately, fixing the cmake output doesn't fix it for the next person.

When I wrote those instructions (updated from a previous iteration), I did verify them with a clean install, but maybe something has changed.

I've fully updated my primary build environment and cloned a new copy of OpenSCAD, and cmake runs OK, but that's not the same as a fresh install.  I'll do a fresh install on a spare system, but first could you please supply the output from `pacman -Q`?

**Comment by Paulwhy2** [comment]
Thanks Jordan,
I still get error messages from Cmake:

-- Checking for one of the modules 'glib-2.0'
CMake Error at C:/msys64/mingw64/share/cmake/Modules/FindPkgConfig.cmake:894 (message):
  None of the required 'glib-2.0' found

and

-- Checking for one of the modules 'glew'
CMake Error at cmake/Modules/FindGLEW.cmake:64 (message):
  GLEW not found

Here is pacman -Q:
$ pacman -Q
base 2020.12-1
bash 5.1.016-1
bash-completion 2.11-2
binutils 2.37-5
bison 3.8.2-3
brotli 1.0.9-3
bsdtar 3.6.1-2
bzip2 1.0.8-3
ca-certificates 20211016-1
cmake 3.23.2-1
coreutils 8.32-2
curl 7.83.1-1
dash 0.5.11.5-2
db 5.3.28-3
file 5.41-4
filesystem 2022.01-4
findutils 4.9.0-3
flex 2.6.4-2
gawk 5.1.1-1
gcc 11.3.0-2
gcc-libs 11.3.0-2
gdbm 1.23-1
getent 2.18.90-3
gettext 0.21-2
git 2.37.2-1
gmp 6.2.1-2
gnupg 2.2.35-1
grep 1~3.0-3
gzip 1.12-1
heimdal 7.7.0-3
heimdal-libs 7.7.0-3
inetutils 1.9.4-3
info 6.8-4
isl 0.25-2
jsoncpp 1.9.5-1
less 590-1
libarchive 3.6.1-2
libargp 20110921-3
libasprintf 0.21-2
libassuan 2.5.5-1
libbz2 1.0.8-3
libcbor 0.9.0-1
libcrypt 2.1-3
libcurl 7.83.1-1
libdb 5.3.28-3
libedit 20210910_3.1-1
libexpat 2.4.8-1
libffi 3.4.2-1
libfido2 1.10.0-1
libgcrypt 1.10.1-4
libgdbm 1.23-1
libgettextpo 0.21-2
libgnutls 3.7.6-1
libgpg-error 1.45-1
libgpgme 1.17.1-1
libhogweed 3.7.3-2
libiconv 1.16-2
libidn2 2.3.2-3
libintl 0.21-2
libksba 1.6.0-1
liblz4 1.9.3-2
liblzma 5.2.5-2
libnettle 3.7.3-2
libnghttp2 1.47.0-2
libnpth 1.6-1
libopenssl 1.1.1.o-1
libp11-kit 0.24.1-3
libpcre 8.45-1
libpcre2_8 10.40-1
libpsl 0.21.1-4
libreadline 8.1.002-2
librhash 1.4.2-1
libsqlite 3.38.5-1
libssh2 1.10.0-1
libtasn1 4.18.0-3
libunistring 1.0-1
libutil-linux 2.35.2-1
libuv 1.42.0-1
libxml2 2.9.14-3
libxslt 1.1.35-2
libzstd 1.5.2-2
m4 1.4.19-2
make 4.3-3
mingw-w64-x86_64-SDL2 2.0.22-2
mingw-w64-x86_64-aom 3.4.0-1
mingw-w64-x86_64-binutils 2.39-2
mingw-w64-x86_64-boost 1.79.0-4
mingw-w64-x86_64-brotli 1.0.9-5
mingw-w64-x86_64-bzip2 1.0.8-2
mingw-w64-x86_64-c-ares 1.18.1-1
mingw-w64-x86_64-ca-certificates 20211016-3
mingw-w64-x86_64-cairo 1.17.6-2
mingw-w64-x86_64-cgal 5.2-3
mingw-w64-x86_64-cmake 3.24.0-1
mingw-w64-x86_64-crt-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-curl 7.84.0-2
mingw-w64-x86_64-dav1d 1.0.0-1
mingw-w64-x86_64-dbus 1.12.20-5
mingw-w64-x86_64-djvulibre 3.5.28-2
mingw-w64-x86_64-double-conversion 3.2.0-1
mingw-w64-x86_64-eigen3 3.4.0-1
mingw-w64-x86_64-expat 2.4.8-1
mingw-w64-x86_64-fftw 3.3.10-3
mingw-w64-x86_64-flif 0.4-1
mingw-w64-x86_64-fontconfig 2.14.0-1
mingw-w64-x86_64-freeglut 3.2.2-2
mingw-w64-x86_64-freetype 2.12.1-1
mingw-w64-x86_64-fribidi 1.0.12-1
mingw-w64-x86_64-gcc 12.1.0-3
mingw-w64-x86_64-gcc-ada 12.1.0-3
mingw-w64-x86_64-gcc-fortran 12.1.0-3
mingw-w64-x86_64-gcc-libgfortran 12.1.0-3
mingw-w64-x86_64-gcc-libs 12.1.0-3
mingw-w64-x86_64-gcc-objc 12.1.0-3
mingw-w64-x86_64-gdb 12.1-3
mingw-w64-x86_64-gdb-multiarch 12.1-3
mingw-w64-x86_64-gdk-pixbuf2 2.42.9-1
mingw-w64-x86_64-gettext 0.21-3
mingw-w64-x86_64-ghostscript 9.53.3-2
mingw-w64-x86_64-giflib 5.2.1-3
mingw-w64-x86_64-glew 2.2.0-2
mingw-w64-x86_64-glib2 2.72.3-2
mingw-w64-x86_64-gmp 6.2.1-3
mingw-w64-x86_64-gnutls 3.7.7-1
mingw-w64-x86_64-graphite2 1.3.14-2
mingw-w64-x86_64-gsfonts 20200910-2
mingw-w64-x86_64-harfbuzz 5.1.0-1
mingw-w64-x86_64-headers-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-icu 69.1-1
mingw-w64-x86_64-imagemagick 7.1.0.39-1
mingw-w64-x86_64-isl 0.25-1
mingw-w64-x86_64-jansson 2.14-2
mingw-w64-x86_64-jasper 3.0.6-1
mingw-w64-x86_64-jbig2dec 0.19-1
mingw-w64-x86_64-jbigkit 2.1-4
mingw-w64-x86_64-jemalloc 5.2.1-2
mingw-w64-x86_64-jsoncpp 1.9.4-2
mingw-w64-x86_64-lcms2 2.13.1-2
mingw-w64-x86_64-lerc 4.0.0-1
mingw-w64-x86_64-libarchive 3.6.1-2
mingw-w64-x86_64-libb2 0.98.1-2
mingw-w64-x86_64-libde265 1.0.8-3
mingw-w64-x86_64-libdeflate 1.13-1
mingw-w64-x86_64-libffi 3.4.2-2
mingw-w64-x86_64-libgccjit 12.1.0-3
mingw-w64-x86_64-libheif 1.12.0-10
mingw-w64-x86_64-libiconv 1.17-1
mingw-w64-x86_64-libidn 1.40-1
mingw-w64-x86_64-libidn2 2.3.3-1
mingw-w64-x86_64-libjpeg-turbo 2.1.3-1
mingw-w64-x86_64-liblqr 0.4.2-4
mingw-w64-x86_64-libltdl 2.4.7-1
mingw-w64-x86_64-libmangle-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-libmysofa 1.2.1-1
mingw-w64-x86_64-libpaper 1.1.28-1
mingw-w64-x86_64-libpng 1.6.37-6
mingw-w64-x86_64-libpsl 0.21.1-4
mingw-w64-x86_64-libraqm 0.9.0-1
mingw-w64-x86_64-libraw 0.20.2-6
mingw-w64-x86_64-libssh2 1.10.0-1
mingw-w64-x86_64-libsystre 1.0.1-4
mingw-w64-x86_64-libtasn1 4.18.0-1
mingw-w64-x86_64-libtiff 4.4.0-5
mingw-w64-x86_64-libtre-git r128.6fb7206-2
mingw-w64-x86_64-libunistring 1.0-1
mingw-w64-x86_64-libuv 1.42.0-3
mingw-w64-x86_64-libwebp 1.2.4-1
mingw-w64-x86_64-libwinpthread-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-libwmf 0.2.12-4
mingw-w64-x86_64-libxml2 2.9.14-4
mingw-w64-x86_64-libzip 1.9.2-1
mingw-w64-x86_64-llvm 14.0.6-3
mingw-w64-x86_64-lz4 1.9.3-1
mingw-w64-x86_64-lzo2 2.10-2
mingw-w64-x86_64-make 4.3-1
mingw-w64-x86_64-md4c 0.4.8-2
mingw-w64-x86_64-mesa 22.1.6-1
mingw-w64-x86_64-mpc 1.2.1-1
mingw-w64-x86_64-mpdecimal 2.5.1-1
mingw-w64-x86_64-mpfr 4.1.0.p13-1
mingw-w64-x86_64-ncurses 6.3-5
mingw-w64-x86_64-nettle 3.8.1-1
mingw-w64-x86_64-nghttp2 1.48.0-1
mingw-w64-x86_64-ninja 1.11.0-1
mingw-w64-x86_64-openal 1.22.2-1
mingw-w64-x86_64-opencsg 1.4.2-2
mingw-w64-x86_64-openjpeg2 2.5.0-2
mingw-w64-x86_64-openssl 1.1.1.q-1
mingw-w64-x86_64-p11-kit 0.24.1-3
mingw-w64-x86_64-pcre 8.45-1
mingw-w64-x86_64-pcre2 10.40-1
mingw-w64-x86_64-pixman 0.40.0-2
mingw-w64-x86_64-pkgconf 1.8.0-2
mingw-w64-x86_64-python 3.10.6-1
mingw-w64-x86_64-qscintilla 2.13.3-2
mingw-w64-x86_64-qt5-base 5.15.3+kde+r174-2
mingw-w64-x86_64-qt5-multimedia 5.15.3-1
mingw-w64-x86_64-qt5-svg 5.15.3+kde+r12-1
mingw-w64-x86_64-rav1e 0.5.1-3
mingw-w64-x86_64-readline 8.1.002-2
mingw-w64-x86_64-rhash 1.4.2-1
mingw-w64-x86_64-sqlite3 3.39.2-1
mingw-w64-x86_64-tcl 8.6.11-5
mingw-w64-x86_64-termcap 1.3.1-6
mingw-w64-x86_64-tk 8.6.11.1-2
mingw-w64-x86_64-tools-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-ttf-dejavu 2.37-3
mingw-w64-x86_64-tzdata 2022a-1
mingw-w64-x86_64-vulkan-headers 1.3.223-1
mingw-w64-x86_64-vulkan-loader 1.3.223-1
mingw-w64-x86_64-windows-default-manifest 6.4-4
mingw-w64-x86_64-wineditline 2.205-3
mingw-w64-x86_64-winpthreads-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-winstorecompat-git 10.0.0.r62.gafef638c3-1
mingw-w64-x86_64-x265 3.5-3
mingw-w64-x86_64-xxhash 0.8.1-2
mingw-w64-x86_64-xz 5.2.6-1
mingw-w64-x86_64-zlib 1.2.12-1
mingw-w64-x86_64-zstd 1.5.2-2
mintty 1~3.6.1-1
mpc 1.2.1-1
mpfr 4.1.0.p13-1
msys2-keyring 1~20220522-1
msys2-launcher 1.5-1
msys2-runtime 3.3.5-2
msys2-runtime-devel 3.3.5-3
msys2-w32api-headers 10.0.0.r16.g49a56d453-1
msys2-w32api-runtime 10.0.0.r16.g49a56d453-1
nano 6.3-1
ncurses 6.3-3
nettle 3.7.3-2
openssh 8.9p1-3
openssl 1.1.1.o-1
p11-kit 0.24.1-3
pacman 6.0.1-15
pacman-contrib 1.5.1-1
pacman-mirrors 20220205-1
perl 5.32.1-2
perl-Authen-SASL 2.16-2
perl-Clone 0.45-2
perl-Convert-BinHex 1.125-1
perl-Encode-Locale 1.05-1
perl-Error 0.17029-1
perl-File-Listing 6.15-1
perl-HTML-Parser 3.78-1
perl-HTML-Tagset 3.20-2
perl-HTTP-Cookies 6.10-1
perl-HTTP-Daemon 6.14-1
perl-HTTP-Date 6.05-1
perl-HTTP-Message 6.36-1
perl-HTTP-Negotiate 6.01-2
perl-IO-HTML 1.004-1
perl-IO-Socket-SSL 2.074-1
perl-IO-Stringy 2.113-1
perl-LWP-MediaTypes 6.04-1
perl-MIME-tools 5.509-1
perl-MailTools 2.21-1
perl-Net-HTTP 6.22-1
perl-Net-SMTP-SSL 1.04-1
perl-Net-SSLeay 1.90-1
perl-TermReadKey 2.38-2
perl-TimeDate 2.33-1
perl-Try-Tiny 0.31-1
perl-URI 5.10-1
perl-WWW-RobotRules 6.02-2
perl-libwww 6.60-1
pinentry 1.2.0-1
pkgconf 1.8.0-1
rebase 4.5.0-2
sed 4.8-3
tcl 8.6.10-1
tftp-hpa 5.2-4
time 1.9-3
tzcode 2022a-1
util-linux 2.35.2-1
wget 1.21.3-1
which 2.21-4
windows-default-manifest 6.4-1
xz 5.2.5-2
zlib 1.2.12-2
zstd 1.5.2-2

**Comment by jordanbrown0** [comment]
Your environment looks considerably older than mine.  (Admittedly, I just updated mine today.)

Mine: base 2022.06-1
Yours: base 2020.12-1

And lots of other differences.

I suggest that you `pacman -Syu`.  I don't know whether you need to do it repeatedly.

Make sure that you have all of the dependencies:
```
$ curl -L https://github.com/openscad/openscad/raw/master/scripts/msys2-install-dependencies.sh | sh 
```

(Or since you already have an OpenSCAD repo, you could just run scripts/msys2-install-dependencies.sh .)

**Comment by jordanbrown0** [comment]
For instance:  I don't know whether it's truly relevant, but I have a "glib2" that you don't have.

**Comment by Paulwhy2** [comment]
Thanks, Jordan.  I won't be able to work on this project until next
weekend.  I'll try this and respond then.

**Comment by Paulwhy2** [comment]
I deleted my build and source directories and reinstalled the dependencies, then cmake ran without errors.  I then did a build and ran Openscad from that build.  Everything worked.  Thank you for your help on this.
I'm not sure why I got those cmake errors the first time, but it must have been my mistake.  Perhaps I made a typo, or did something from the wrong directory.
