### ISSUE TITLE
How to mark length ?

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#4664]
![alt](https://www.ttcad.com/upFiles/infoImg/coll/20130619/OT20130619160434033.jpg)

**Comment by t-paul** [comment]
Image is broken and gives error `Cannot proxy the given URL`.

**Comment by sonichy** [comment]
fixed

**Comment by t-paul** [comment]
Still having problems. New link is not reachable.

![grafik](https://github.com/openscad/openscad/assets/1330241/a2ff64b9-4175-49e2-a93a-85666789a2c6)

**Comment by sonichy** [comment]
New link is not any of github !

**Comment by t-paul** [comment]
I know. As the screenshot above shows, the server `ttcad.com` is not reachable from here and the host checker https://downforeveryoneorjustme.com/ agrees too.

Do you have access to sites like imgur.com or imgpile.com or imgbb.com ?

**Comment by sonichy** [comment]
OK, uploaded to imgse.com.

**Comment by jordanbrown0** [comment]
Er... and the URL there is?
