### ISSUE TITLE
Color rendering: Subtracted minkowski isn't using the subtraction color in Manifold mode

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#5218]
The following design subtracts a minkowski object from a simple positive object. The cutout surface should be rendered using the subtractions color (defaults to green), but is instead rendered with the default positive color (yellow):
```
difference() {
  cube(10, center=true);
  translate([5,5,5]) minkowski(convexity=2) {
    cube(8, center=true);
    cube(1, center=true);
  }
}
```

**Comment by pca006132** [comment]
Probably missing an AsOriginal call after minkowski.

**Comment by kintel** [comment]
This was already fixed by #5234 - forgot to close it.

@pca006132 Did you observe similar wrong behavior related to your latest commit in #5282?

**Comment by pca006132** [comment]
yes but it is now fixed as well

**Comment by kintel** [comment]
Reopening this: This is still broken in throwntogether mode, but we didn't include a test for that. Will create a test shortly.

**Comment by kintel** [comment]
How to reproduce:
* Re-enable disabled test here: https://github.com/openscad/openscad/blob/7f35682b4bf278e3d33e3bb8293b5907ec356a29/tests/CMakeLists.txt#L1628
* `ctest -R throwntogether-manifold_issue5218`

**Comment by ali1234** [comment]
Here is a much simpler reproducer for this bug:

```
difference() {
    cube(15, center=true);
    render() difference() {
        cube(20, center=true);
        cube(10, center=true);
    }
}
```

If you remove the `render` call then you get a green cube in thrown together. But with render it is yellow.

~~It happens because of this code in ThrownTogetherRenderer:~~ it isn't that...

If an object has explicit colour data (ie color_indices) then that will be used. Otherwise, ThrownTogetherRenderer chooses the appropriate colour based on other properties.

Since PolySetRenderer previously did not support colour for Nefs, they would have no colour data when they hit the preview and would be coloured automatically.

Now it does support colour, those colours override anything set in the renderer.

So effectively `render()` ends up behaving the same as setting an explicit colour, eg `color("red")`

With Manifold backend, the input to `render()` is not a Nef, so rendering it always resulted in colours being assigned.

**Comment by ali1234** [comment]
Interestingly the reproducer totally fails in normal preview. Nothing is drawn at all.

**Comment by ali1234** [comment]
To explain the problem in a different way, this is what ThrownTogetherRenderer does:

```
For each chunk of geometry:
    If it has explicit colour data:
        it is drawn in that colour
    Else:
        it is drawn green if it is being subtracted, otherwise yellow
```

Normally geometry only has explicit colour if wrapped in a `color()` call.

The problem is some geometry has to be rendered in order to be previewed eg `minkowski()` in the original reproducer, and anything wrapped in a `render()` call. Rendering an object forces it to have explicit colours, except for Nefs for which the converter does not support colour. This is why Manifold always had this bug (it never creates Nefs), and my patch adding Nef colour support causes this bug to affect CGAL as well.

This is tricky because the `render()` call does not know that its result is going to go on to be used in a `difference()` - for that it would need to look above itself in the CSG tree - so it cannot set the "right" colours itself. After it has set explicit colours, the ThrownTogetherRenderer cannot override them (because it does not know if they are from a `color()` or a `render()`).
