### ISSUE TITLE
Multi-color 3mf export broken in 2025.08.18

### ISSUE THREAD

**Issue by dan-p3rry** [openscad/openscad#6159]
**Describe the bug**
Until recently, not sure exactly which openscad version, I could export multicolor .3mf file, import to PrusaSlicer and print.  PrusaSlicer has not been updated recently, but Openscad has, and this ability is gone.

**To Reproduce**
Export code below to a 3mf file, then import to PrusaSlicer.  When working properly, PrusaSlicer should ask to confirm this is multiple parts, then populate the GUI accordingly.  Now PS just imports as a single solid.  NOTE that afaik PS won't import as a multicolor part if you have a single extruder printer.  So to reproduce, you need to configure a multicolor printer such as Prusa XL with 5 toolheads.

**Expected behavior**

**Code reproducing the issue**
```
color("red") cube(10);
color("blue") translate([-10, 0, 0]) cube(10);
```

**Environment and Version info (please complete the following information):**
 - OS: Win 11
 - System: PC
 - OpenSCAD Version 2025.08.18

**Comment by dan-p3rry** [comment]
I downloaded yesterday's version, confirmed that the bug has been fixed, closing.

**Comment by nomike** [comment]
Heads up: this bug is **still present on master** when OpenSCAD is built against `lib3mf 1.x`. The original self-close was almost certainly a lib3mf-version mix-up — the "fixed in yesterday's version" build was likely linked against `lib3mf >= 2`, which uses a separate exporter (`src/io/export_3mf_v2.cc`) that's keyed off a `Color4f -> idx` map and is unaffected. The `lib3mf 1.x` path in `src/io/export_3mf_v1.cc` (still used by most Linux distro packages) keeps a per-export `ExportContext::materialids` vector that gets indexed with a per-mesh-relative `color_index`, so the second mesh's triangles silently resolve to the first mesh's material ID.

Reproduced live against `master @ b38f68881` linked against `lib3MF.so.1` with the exact script from this issue plus `--enable=lazy-union`.

Filed a fresh tracker and a fix:

- New issue: #6813 (full root-cause walk-through + scope)
- Fix PR: #6814 (`materialids` is only ever used within a single `append_polyset` call, so move it from `ExportContext` to a local and pass it as a parameter)

Leaving this issue closed; future search hits should land here and follow the cross-references to the active tracker.
